### ISSUE TITLE
Urgent : couple of doubts need some clarification

### ISSUE THREAD

**Issue by Ng-India99** [PAXSTORE/paxstore-3rd-app-android-sdk#10]
Hi can any on please help us below things sorry for the opening issue, i know its not issue but i dint have other chance to ask.

we have a developer account.

1.how to enable debugging options in PAX A920 device? 

2. how to get the paydroid-Neptune SDK   ?

**Comment by fojut** [comment]
Please create your question on PPN, where you can get the efficient support.
