### ISSUE TITLE
StoreSDK returns I/onError:: android.os.RemoteException: Not allowed to get terminal information from PAXSTORE

### ISSUE THREAD

**Issue by lborsato** [PAXSTORE/paxstore-3rd-app-android-sdk#13]
StoreSDK.init() is successful, but when I call getBaseTerminalInfo() or startLocate() I get:

   android.os.RemoteException: Not allowed to get terminal information from PAXSTORE

This happens when I run the demo as well. Any idea why this is happening?

**Comment by fojut** [comment]
Hi @lborsato, that's befacuse the reseller/merchant don't allow external application to get terminal information.
You can ask them whether it is possible to enable this feature in their profile.
