### ISSUE TITLE
How could Integrate SDK to project xamarin form?

### ISSUE THREAD

**Issue by Herson95** [PAXSTORE/paxstore-3rd-app-android-sdk#2]
Hi, I would like to know if we could help how to integrate the sdk, a project in xamarin

**Comment by Ng-India99** [comment]
@Herson95  hi, Did you find the solution for integrating in xamarin or ionic application ??

**Comment by fojut** [comment]
As I known, Xamarin also provides facilities for directly invoking Objective-C, Java, C, and C++ libraries, giving you the power to use a wide array of third party code. This functionality lets you use existing iOS and Android libraries written in Objective-C, Java, or C/C++.

**Comment by fojut** [comment]
I think all the android hybrid mobile apps have their ways to invoke android libriaries, no matter what framework (Ionic, react native etc.) they choose.
