### ISSUE TITLE
Reboot terminal

### ISSUE THREAD

**Issue by oliveira-marcello** [PAXSTORE/paxstore-3rd-app-android-sdk#22]
Hi, we have a self-checkout app, and the ability to reboot the terminal would be of huge value to us.

Rebooting the terminal solve the most common problems that we encounter. We often have internet connection issues that require a APN reconfiguration that is performed when the terminal reboots. Or sometimes the service that we use for payment (which we don't control) stops responding, and rebooting the terminal fixes it. Every other problem that we've encoutered were also fixed by rebooting the terminal.

Because or app is used for self-checkout, there is no one present to manually reboot it. Rebooting via the PAXSTORE Administrator Center also won't help if the terminal is offline.

Is there any possibility of rebooting the terminal using the SDK?

**Comment by zimuouyang** [comment]
Sorry, restarting the terminal is a high-privilege and high-risk operation, and this SDK has no support plan
