### ISSUE TITLE
Updates made via PAXSTORE do not immediately take effect

### ISSUE THREAD

**Issue by alvindizon** [PAXSTORE/paxstore-3rd-app-android-sdk#7]
Whenever I try to push an update to my app, either via "Push app" or "Push app template", I noticed that the update does not immediately get pushed to the terminal. I have to restart the terminal, and open the PAXSTORE app in order to receive the update. Is this the expected behavior?

I am using a PAX A920.

**Comment by fojut** [comment]
Do you still have this issue? Please try it by using the latest store client.

**Comment by alvindizon** [comment]
Hi @fojut , thanks for answering. This issue is quite old, we're not encountering this issue anymore. We're using version 6.3.1
