### ISSUE TITLE
Unresolved dependency to com.google.gson

### ISSUE THREAD

**Issue by jheydebrand** [PAXSTORE/paxstore-3rd-app-android-sdk#8]
When importing the SDK as module into another project that uses the latest gradle wrapper (https://services.gradle.org/distributions/gradle-5.1.1-all.zip) and Android gradle plugin ('com.android.tools.build:gradle:3.4.1'), the PAX SDK module fails to build because com.google.gson cannot be found.

Adding 
```implementation 'com.google.code.gson:gson:2.8.5'```
to the SDK's build.gradle file fixes this problem.

**Comment by fojut** [comment]
Please use the latest SDK version that has included gson dependency.
